# Generated by Django 4.0.1 on 2024-05-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=12)),
                ('delivery_address', models.CharField(max_length=255)),
                ('order_product', models.JSONField()),
                ('total_price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('isDone', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('customer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-date'],
            },
        ),
    ]
