# Generated by Django 4.0.1 on 2024-05-06 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('nguoidung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.nguoidung')),
                ('delivery_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customser',
            },
            bases=('user.nguoidung',),
        ),
    ]
